# -*- coding: utf-8 -*-
"""text_generationjs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1go99OJKSnlAaNL0QH81c2tDGPZPpicVk
"""



"""let charRNN;
let textInput;
let loaded;

function setup() {
  createCanvas(400,400);
  
  input = createInput();
  input.position(20,65);
  
  button = createButton('submit');
  button.position(input.x + input.width, 65);
  button.mousePressed(generateText);
  loaded = true;
  charRNN = ml5.charRNN('https://github.com/ikennannaji/Text-Generation-with-CharRNN-/blob/main/mad', modelReady);
  
  background('white')
  text("Training",10,20);
}

function modelReady() {
  loaded = false;
  background("white");
  text("Ready",10,20)
}

function generateText() {
  const original = input.value();
  const txt = original.toLowerCase();

  if(!loaded && txt.length > 0) {
    const data = {
      seed: txt,
      temperature: 0.9,
      length: 20,
    };

    charRNN.generate(data, gotData);
  }
}

function gotData(err, result) {
  if (err){
    console.error(err);
    return;
  }
  background('white');
  text(input.value().toLowerCase() + result.sample, 10, 40);
}
"""